module.exports = {
  // redirect-from: redirect-to
  '/landmine': '/capstone/landmine',
  '/projectUnison': '/capstone/unison',
  '/projectrevision': '/capstone/revision',
  '/gpt': '/capstone/gpt',
  '/team': '/about#team',
  '/competitions': '/competitions/sr',
  '/contests': '/courses/competitions-sr',
  '/courses': '/courses/fall',
  '/winterbreak': '/courses/winterbreak',
  '/summer': '/courses/summer',
  '/bridgelab': '/sprint/bridgelab',
  '/aura': '/capstone/aura',
  '/resq': '/capstone/resq',
  '/bridgemun': '/capstone/bridgemun',
  '/aura_en': '/capstone/aura_en',
  '/resq_en': '/capstone/resq_en',
  '/bridgemun_en': '/capstone/bridgemun_en',
  '/contactUs': '/contact-us',
  '/fall': '/courses/fall',
};
